### ISSUE TITLE
R seesion crash in `fmQueryComputeAntTajectories` with `reportTrajectories = F`

### ISSUE THREAD

**Issue by atuleu** [formicidae-tracker/myrmidon#163]
Probably a SEGFAULT

Needs proper unit testing

**Comment by atuleu** [comment]
Thois comes from the fact that summarizing is happening before trajectory termination. Since one of the behavior happens in the C++ code (termination) and the other form the R side (summarizing) it is almost impossible to test it properly.

All this logic should be expressed from the C++ API, and the bindings needs to be a mere simple wrapper.

**Comment by nathaliestroeymeyt** [comment]
Should the title of this bug be R session crash in fmQueryComputeAntInteractions (rather than fmQueryComputeAntTrajectories)? I don't think there's a reportTrajectories argument in fmQueryComputeAntTrajectories...

Regardless, the bug is still present today: fmQueryComputeAntInteractions throws a series of errors related to process_memory_range, elf_image_reader, elf_dynamic_array_reader, directory_reader_posix.cc then makes R crash when reportTrajectories = T

**Comment by atuleu** [comment]
Fixed in v0.8.0
