### ISSUE TITLE
Adds a public API to list change of a metadata key over time for a given Ant

### ISSUE THREAD

**Issue by atuleu** [formicidae-tracker/myrmidon#218]
**Is your feature request related to a problem? Please describe.**

The metadata key is a powerful mechanism to encode a variety of information. For example it can be used to tag time range where an ant is showing a given behavior. By example, one can create a boolean key 'isGrooming' and set this value to `true` whenever an ant starts to groom and set it back to false once it is done. If someone is marking the behavior of the ant this way, there is no public API vailable to retrieve the time range where an Ant is grooming.

**Describe the solution you'd like**
Add these two methods:
* a `std::map<fort::Time,fort::myrmidon::AntStaticValue> fort::myrmidon::Ant::GetVallueChanges(const std::string & key)` method for `Ant` that gives the list of changes over time of a given metadatakey for an Ant
* a `std::vector<std::tuple<fort::myrmidon::AntID,fort::Time,fort::Time>> fort::myrmidon::Query::GetMetaDataRanges(const std::string & key, const fort::myrmidon::AntStaticValue & value)` query that returns a list of time range and antID where these ants have `key` equal to `value`.

**Comment by atuleu** [comment]
@matthiasruegg : Following our discussion, could I request your comment on this feature ?

**Comment by matthiasruegg** [comment]
Both functions make sense to me with a priority for the first one. Characterizing individuals according to different recorded behavioral events over the entire experiment will be a likely use case. Since afaik the ant metadata is stored in the ant object with a (timestamp, changed value) tuple, I assume the technical implications for the second option would simply be a wrapper for the first and therefore with filtering according to timestamp. Therefore not much additional work, is that correct?
