### ISSUE TITLE
R bindings should correctly cast `integer`/`numeric` to `fmDuration` or raise an error instead

### ISSUE THREAD

**Issue by AdrianoWanderlingh** [formicidae-tracker/myrmidon#242]
**Describe the bug**
fmMatcherAntDisplacement assigns arbitrary minimumGap in R, regardless the input value. The package vignette does not inform on the time format (I assume seconds) to be used in the function.

**To Reproduce**
1. run `fmMatcherAntDisplacement(ANT_LENGHT_PX, 1) ))`

2. ERROR in attributed minimumGap when the object is called:
`>AntDisplacement(under: 153, minimumGap: 78h11m10.966956032s) `
this assigned gap doesn't change when using another value as input.

3. ERROR when outside of the numeric boundary 1-52 : 
```
>Error in fmMatcherAntDisplacement(ANT_LENGHT_PX, 53) : 
 Cannot convert object to an environment: [type=double; target=ENVSXP].
```

**Expected behavior**
a time in seconds is stored as minimumGap.

**Affected packages**
Please select one or more package by putting a `x` in the brackets

- [ ] `libfort-myrmidon` installed from `conda`
- [ ] `py_fort_myrmidon`installed from `conda`
- [x] `r-fort-myrmidon` installed from `conda`
- [ ] `fort-studio` installed from  `snap`
- [ ] `fort-studio` installed from `conda`

**Installed version**
FortMyrmidon version 0.8.1

**Comment by atuleu** [comment]
Jôaésaq

**Comment by atuleu** [comment]
Indeed the documentation is lacking the expected type for minimumGap. It looks for a `fmDuration`. As a general design philosophy, all input time representation of `fort-myrmidon` are `fmTime` / `fmDuration`.

However the issue here is that passing  `1` to a function requiring a `fmDuration`,  should either implicitly cast the value to a valid `fmDuration`, or raise an error because a `fmDuration` should be expected and an `integer`, `logical`, or `numeric` has been passed instead.

**Comment by AdrianoWanderlingh** [comment]
I should have tried with the fmDuration, thanks for pointing that out.
